version: '2'

services:
    nginx:
        image: wiwatsrt/docker-laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www
            - ./sites:/etc/nginx/sites-enabled
            - ./logs/nginx:/var/log/nginx
        links: 
            - php7fpm 
        depends_on: 
            - php7fpm
            - mysql

    artisan:
        image: wiwatsrt/docker-laravel-artisan
        volumes:
            - ./www:/var/www
        links: 
            - mysql
        depends_on: 
            - mysql

    composer:  
        image: wiwatsrt/docker-laravel-composer
        volumes:
            - ./www:/var/www

    php7fpm:
        image: wiwatsrt/docker-laravel-php7fpm
        volumes:
            - ./www:/var/www
        links:
            - mysql

    mysql:
        image: wiwatsrt/docker-laravel-mariadb
        volumes:
            - ./database:/var/lib/mysql
            - ./logs/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret

    nodejs:  
        image: wiwatsrt/docker-laravel-nodejs
        volumes:
            - ./www:/var/www

volumes:
    sites:
        driver: local
    www:
        driver: local
    database:
        driver: local
    logs:
        driver: local